/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cronometro;

import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author MARTHA
 */
public class Cronometro extends javax.swing.JFrame {
    private Timer tiempo;
    private int centesimaSegundos=0, segundos=0,minutos=0,horas=0;
    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            
            centesimaSegundos++;
            
            if(centesimaSegundos==100){
                
                segundos++;
                centesimaSegundos=0;
                
            }
            if(segundos==60){
                minutos++;
                segundos=0;
            }
            if(minutos==60){
                horas++;
                minutos=0;
            }
            
            actualizarEtiquetaTiempo();
            
        }
    };
    
    private void actualizarEtiquetaTiempo(){
        
        String texto = (horas<=9?"0":"")+horas+":"+(minutos<=9?"0":"")+minutos+":"+(segundos<=9?"0":"")+segundos+":"+(centesimaSegundos<=9?"0":"")+centesimaSegundos;
        EtiquetaTiempo.setText(texto);
    }
    /**
     * Creates new form Cronometro
     */
    public Cronometro() {
        initComponents();
        setLocationRelativeTo(null);
        tiempo = new Timer(10,acciones);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        imagenCronometro = new javax.swing.JLabel();
        EtiquetaCronometro = new javax.swing.JLabel();
        BotonIniciar = new javax.swing.JButton();
        EtiquetaTiempo = new javax.swing.JLabel();
        BotonPausar = new javax.swing.JButton();
        BotonDetener = new javax.swing.JButton();
        EtiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronometro");
        setResizable(false);

        Panel.setPreferredSize(new java.awt.Dimension(800, 300));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenCronometro.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\Cronometro\\src\\main\\java\\Imagenes\\cronometro2.png")); // NOI18N
        Panel.add(imagenCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 256, 256));

        EtiquetaCronometro.setBackground(new java.awt.Color(255, 255, 255));
        EtiquetaCronometro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EtiquetaCronometro.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaCronometro.setText("CRONOMETRO");
        Panel.add(EtiquetaCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        BotonIniciar.setBackground(new java.awt.Color(255, 204, 204));
        BotonIniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonIniciar.setText("Iniciar");
        BotonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarActionPerformed(evt);
            }
        });
        Panel.add(BotonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 120, -1));

        EtiquetaTiempo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        EtiquetaTiempo.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaTiempo.setText("00:00:00:00");
        Panel.add(EtiquetaTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 340, 90));

        BotonPausar.setBackground(new java.awt.Color(255, 204, 204));
        BotonPausar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonPausar.setText("Pausar");
        BotonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPausarActionPerformed(evt);
            }
        });
        Panel.add(BotonPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 110, -1));

        BotonDetener.setBackground(new java.awt.Color(255, 204, 204));
        BotonDetener.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonDetener.setText("Detener");
        BotonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDetenerActionPerformed(evt);
            }
        });
        Panel.add(BotonDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 110, -1));

        EtiquetaFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\Cronometro\\src\\main\\java\\Imagenes\\fondo.png")); // NOI18N
        EtiquetaFondo.setPreferredSize(new java.awt.Dimension(800, 300));
        Panel.add(EtiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarActionPerformed
        // TODO add your handling code here:
        tiempo.start();
        BotonIniciar.setEnabled(false);
        BotonIniciar.setText("Reanudar");
        BotonPausar.setEnabled(true);
        BotonDetener.setEnabled(true);
        
    }//GEN-LAST:event_BotonIniciarActionPerformed

    private void BotonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPausarActionPerformed
        // TODO add your handling code here:
        tiempo.stop();
        BotonIniciar.setEnabled(true);
        BotonPausar.setEnabled(false);
    }//GEN-LAST:event_BotonPausarActionPerformed

    private void BotonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDetenerActionPerformed
        // TODO add your handling code here:
        if(tiempo.isRunning()){
            tiempo.stop();
            BotonIniciar.setEnabled(true);
        }
        BotonIniciar.setText("Iniciar");
        BotonPausar.setEnabled(false);
        BotonDetener.setEnabled(false);
        
        horas = 0;
        minutos = 0;
        segundos = 0;
        centesimaSegundos = 0;
        
        actualizarEtiquetaTiempo();
    }//GEN-LAST:event_BotonDetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cronometro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDetener;
    private javax.swing.JButton BotonIniciar;
    private javax.swing.JButton BotonPausar;
    private javax.swing.JLabel EtiquetaCronometro;
    private javax.swing.JLabel EtiquetaFondo;
    private javax.swing.JLabel EtiquetaTiempo;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel imagenCronometro;
    // End of variables declaration//GEN-END:variables
}
